### ISSUE TITLE
Short Example games in both adv3 and adv3Litr

### ISSUE THREAD

**Issue by EricEve** [tads-intfic/tads3-website#3]
```yaml
- title: Example Games
  type: Adv3 and Adv3Lite
  author: Eric Eve
  description: A set of ten short games illustrating how to  use various parts of the library in both adv3 and adv3Lite
  url: https://users.ox.ac.uk/~manc0049/TADSGuide/Examples/exercises.htm
```
```yaml
- title  Cloak of Darkness
  type: Adv3 & adv3Lite 
  author: Eric Eve
  description: Implementations of the Cloak of Darkness game in adv3Lite and adv3
  url: https://users.ox.ac.uk/~manc0049/TADSGuide/cloak.htm
```
