### ISSUE TITLE
Further Information on adv3Lite

### ISSUE THREAD

**Issue by EricEve** [tads-intfic/tads3-website#4]
```yaml
- title: Information about adv3Lite
  type: adv3Lite  
  author: Eric Eve
  description: The original home page of adv3Lite  giving a description of what it's for, how if differs from adv3, and links to various useful resources.
  url: https://users.ox.ac.uk/~manc0049/TADSGuide/adv3Lite.htm
```
I suggest that description of adv3Lite on https://tads.dev/ be changed to match that on my web page, namely:

"Adv3Lite aims to provide a library that's easier to use than the adv3 library which comes standard with TADS 3, but which is almost as powerful and expressive. Adv3Lite misses out the bits that most games don't really need (like postures, room parts, and multiple light levels) while adding in some other bits that are often more useful (like scenes and regions, "borrowed" from Inform 7). Adv3Lite also cuts down drastically on the complexity of the adv3 class hierarchy (there are lots of classes to learn about in adv3!) while maintaining much of their functionality."
